CREATE TABLE ACCOUNT(id INT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(32) NOT NULL DEFAULT '',
	balance DOUBLE NOT NULL DEFAULT 0) CHARACTER SET utf8;
	
INSERT INTO ACCOUNT VALUES(NULL, '马云', 3000), (NULL, '马化腾', 10000);

SELECT * FROM ACCOUNT;


CREATE TABLE admin2(
	id INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL
);
SELECT COUNT(*) FROM admin2;

DROP TABLE admin2;